# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=1024)),
                ('manager', models.CharField(max_length=64)),
                ('use_time', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
                ('privtekey', models.CharField(max_length=1024)),
                ('publickey', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
